export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR'
export const FETCH_MOVIES_COMPLETE = 'FETCH_MOVIES_COMPLETE'

export const FETCH_MOVIES_BY_CATEGORY = 'FETCH_MOVIES_BY_CATEGORY'
export const FETCH_MOVIES_BY_CATEGORY_MORE = 'FETCH_MOVIES_BY_CATEGORY_MORE'

export const FETCH_USER_SESSION_REQUEST = 'FETCH_USER_SESSION_REQUEST'
export const FETCH_USER_SESSION_SUCCESS = 'FETCH_USER_SESSION_SUCCESS'
export const FETCH_USER_SESSION_ERROR = 'FETCH_USER_SESSION_ERROR'

export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS'

export const FETCH_MOVIE_SEARCH = 'FETCH_MOVIE_SEARCH'
